# Generated by Django 4.0.2 on 2022-02-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleMaps',
            new_name='GoogleMap',
        ),
    ]
