# Generated by Django 4.0.2 on 2022-02-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_googlemaps_googlemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemap',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
