# Generated by Django 4.0.2 on 2022-02-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_googlemap_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleMap',
            new_name='Location',
        ),
    ]
