# Generated by Django 4.0.2 on 2022-02-17 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_restaurant_restaurantimage_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.restaurant'),
        ),
    ]
