# Generated by Django 4.0.3 on 2022-05-03 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_restaurant_created_restaurant_date_restaurant_edited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_user.jpg', upload_to='user/profile/%Y/%m/%d/')),
                ('phonenumber', models.PositiveBigIntegerField(blank=True, default=0)),
                ('state', models.CharField(blank=True, default='Maharashtra', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.PositiveIntegerField(blank=True, default=400709)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
