# Generated by Django 4.0.3 on 2022-05-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
