# Generated by Django 4.0.3 on 2022-05-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='good_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='great_ambience',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='great_food',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hygiene_and_cleanliness',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='resonable_cost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='satisfactory_staff',
            field=models.BooleanField(default=True),
        ),
    ]
