# Generated by Django 4.0.3 on 2022-05-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_restaurant_good_service_restaurant_great_ambience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='good_service',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='great_ambience',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='great_food',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='hygiene_and_cleanliness',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='resonable_cost',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='satisfactory_staff',
        ),
    ]
