# Generated by Django 4.0.3 on 2022-05-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_restaurantfeatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantFeatures',
            new_name='RestaurantFeature',
        ),
    ]
