# Generated by Django 4.0.3 on 2022-05-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_restaurantfeatures_restaurantfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='date',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='start_time',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantfeature',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.restaurant'),
        ),
    ]
