# Generated by Django 4.0.3 on 2022-05-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_restaurant_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
