# Generated by Django 4.0.3 on 2022-05-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_restaurant_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
